######################################################################
# Automatically generated by qmake (3.0) Mon May 1 15:31:44 2017
######################################################################

TEMPLATE = app
TARGET = qtest
INCLUDEPATH += .

# Input
SOURCES += quat.cpp
